"""add AP tables and item expense_account

Revision ID: 59d79ed503ca
Revises: bc3556480aa8
Create Date: 2026-08-12 22:03:08.787225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d79ed503ca'
down_revision: Union[str, None] = 'bc3556480aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gst_reg_no', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'PARTIALLY_PAID', 'PAID', 'VOID', name='billstatus', native_enum=False, length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_bills_journal_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_bills_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills')),
    sa.UniqueConstraint('number', name=op.f('uq_bills_number'))
    )
    op.create_table('debit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='debitnotestatus', native_enum=False, length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_debit_notes_journal_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_debit_notes_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debit_notes')),
    sa.UniqueConstraint('number', name=op.f('uq_debit_notes_number'))
    )
    op.create_table('payments_made',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'PAYNOW', 'CARD', 'OTHER', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('POSTED', 'VOID', name='paymentmadestatus', native_enum=False, length=20), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_made_positive')),
    sa.ForeignKeyConstraint(['bank_account_id'], ['accounts.id'], name=op.f('fk_payments_made_bank_account_id_accounts')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_payments_made_journal_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_payments_made_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments_made')),
    sa.UniqueConstraint('number', name=op.f('uq_payments_made_number'))
    )
    op.create_table('debit_note_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit_note_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_debit_note_allocations_positive')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_debit_note_allocations_bill_id_bills')),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.id'], name=op.f('fk_debit_note_allocations_debit_note_id_debit_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debit_note_allocations')),
    sa.UniqueConstraint('debit_note_id', 'bill_id', name=op.f('uq_debit_note_allocations_debit_note_id'))
    )
    op.create_table('payment_made_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_made_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_made_allocations_positive')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_payment_made_allocations_bill_id_bills')),
    sa.ForeignKeyConstraint(['payment_made_id'], ['payments_made.id'], name=op.f('fk_payment_made_allocations_payment_made_id_payments_made'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_made_allocations')),
    sa.UniqueConstraint('payment_made_id', 'bill_id', name=op.f('uq_payment_made_allocations_payment_made_id'))
    )
    op.create_table('bill_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tax_code_id', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_lines_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], name=op.f('fk_bill_lines_expense_account_id_accounts')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_bill_lines_item_id_items')),
    sa.ForeignKeyConstraint(['tax_code_id'], ['tax_codes.id'], name=op.f('fk_bill_lines_tax_code_id_tax_codes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_lines'))
    )
    op.create_table('debit_note_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit_note_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tax_code_id', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.id'], name=op.f('fk_debit_note_lines_debit_note_id_debit_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], name=op.f('fk_debit_note_lines_expense_account_id_accounts')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_debit_note_lines_item_id_items')),
    sa.ForeignKeyConstraint(['tax_code_id'], ['tax_codes.id'], name=op.f('fk_debit_note_lines_tax_code_id_tax_codes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debit_note_lines'))
    )
    op.add_column('items', sa.Column('expense_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_items_expense_account_id_accounts'), 'items', 'accounts', ['expense_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_expense_account_id_accounts'), 'items', type_='foreignkey')
    op.drop_column('items', 'expense_account_id')
    op.drop_table('debit_note_lines')
    op.drop_table('bill_lines')
    op.drop_table('payment_made_allocations')
    op.drop_table('debit_note_allocations')
    op.drop_table('payments_made')
    op.drop_table('debit_notes')
    op.drop_table('bills')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
